name: PHP Lint

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: PHP Lint
        run: |
          find . -type f -name "*.php" -print0 | xargs -0 -I{} php -l {} || exit 1
