name: Deploy to WordPress.org

on:
  push:
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@v3
        with:
          # Слаг плагіна на wp.org 
          plugin_slug: alb-hpp-donations

          build_dir: alb-hpp-donations
          # Куди лежать медіа для сторінки плагіна
          assets_dir: .wordpress-org

          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
